export const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  OPTIONS_READ: 'OPTIONS_READ',
  CUSTOMER_MANAGE: 'CUSTOMER_MANAGE',
  MENU_MANAGE: 'MENU_MANAGE',
  TEMPLATE_MANAGE: 'TEMPLATE_MANAGE',
  DICT_MANAGE: 'DICT_MANAGE',
  USER_MANAGE: 'USER_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE',
}
